# Generated by Django 5.2.8 on 2026-07-18 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_journal_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_goals', models.JSONField(blank=True, default=list, help_text='List of style goal keys from STYLE_GOAL_CHOICES', verbose_name='style goals')),
                ('style_vibe', models.JSONField(blank=True, default=list, help_text='List of vibe keys from VIBE_CHOICES', verbose_name='style vibe')),
                ('fashion_openness', models.CharField(blank=True, choices=[('stick_to_classics', 'I stick to what I know'), ('sometimes_new', 'I try new things sometimes'), ('love_experimenting', 'I love experimenting')], default='', max_length=30, verbose_name='fashion openness')),
                ('lifestyle_tags', models.JSONField(blank=True, default=list, help_text='List of lifestyle keys from LIFESTYLE_CHOICES', verbose_name='lifestyle tags')),
                ('body_type', models.CharField(blank=True, choices=[('hourglass', 'Hourglass'), ('pear', 'Pear'), ('apple', 'Apple'), ('rectangle', 'Rectangle'), ('inverted_triangle', 'Inverted Triangle'), ('prefer_not', 'Prefer not to say')], default='', max_length=25, verbose_name='body type')),
                ('fit_preference', models.CharField(blank=True, choices=[('slim', 'Slim / Fitted'), ('regular', 'Regular'), ('relaxed', 'Relaxed'), ('oversized', 'Oversized')], default='', max_length=15, verbose_name='fit preference')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='height (cm)')),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='weight (kg)')),
                ('skin_tone', models.CharField(blank=True, default='', help_text='Hex color code representing skin tone, e.g. #F5CBA7', max_length=10, verbose_name='skin tone')),
                ('color_palette', models.CharField(blank=True, choices=[('neutral_minimalist', 'Neutral Minimalist'), ('bold_rich', 'Bold & Rich'), ('soft_romantic', 'Soft & Romantic'), ('earthy_warm', 'Earthy & Warm')], default='', max_length=25, verbose_name='color palette')),
                ('clothing_categories', models.JSONField(blank=True, default=dict, help_text='Dict of selected clothing categories. e.g. {"tops":["shirts","hoodies"],"shoes":["sneakers"]}', verbose_name='clothing categories')),
                ('preferred_brands', models.JSONField(blank=True, default=list, help_text='List of brand name strings the user prefers', verbose_name='preferred brands')),
                ('budget_range', models.CharField(blank=True, choices=[('budget', 'Budget (under £30 per item)'), ('mid_range', 'Mid-range (£30–£100)'), ('premium', 'Premium (£100–£300)'), ('luxury', 'Luxury (£300+)')], default='', max_length=15, verbose_name='budget range')),
                ('shopping_frequency', models.CharField(blank=True, choices=[('rarely', 'Rarely (few times a year)'), ('monthly', 'Monthly'), ('bi_weekly', 'Every two weeks'), ('weekly', 'Weekly')], default='', max_length=15, verbose_name='shopping frequency')),
                ('sustainability_preference', models.CharField(blank=True, choices=[('not_important', 'Not important to me'), ('somewhat_important', 'Somewhat important'), ('very_important', 'Very important'), ('only_sustainable', 'I only buy sustainable')], default='', max_length=20, verbose_name='sustainability preference')),
                ('onboarding_completed', models.BooleanField(default=False, help_text='True once user has submitted at least one preference page', verbose_name='onboarding completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user preference',
                'verbose_name_plural': 'user preferences',
            },
        ),
    ]
