# Generated by Django 5.2.8 on 2026-07-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_user_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='fashion_openness',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='fit_preference',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='lifestyle_tags',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='shopping_frequency',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='style_goals',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='style_vibe',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='sustainability_preference',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='body_size',
            field=models.CharField(blank=True, choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL')], default='', max_length=10, verbose_name='body size'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='chest',
            field=models.CharField(blank=True, default='', help_text='Chest size description/measurement', max_length=20, verbose_name='chest size'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='hip',
            field=models.CharField(blank=True, default='', help_text='Hip size description/measurement', max_length=20, verbose_name='hip size'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='shoe_size',
            field=models.CharField(blank=True, default='', help_text='Shoe size description/measurement', max_length=20, verbose_name='shoe size'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='style_match',
            field=models.JSONField(blank=True, default=list, help_text='List of style match keys from STYLE_MATCH_CHOICES', verbose_name='style match'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='waist',
            field=models.CharField(blank=True, default='', help_text='Waist size description/measurement', max_length=20, verbose_name='waist size'),
        ),
    ]
