# Generated by Django 5.2.8 on 2026-07-19 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='cloth name')),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('dresses_outerwear', 'Dresses & Outerwear'), ('accessories', 'Accessories'), ('other', 'Other')], max_length=30, verbose_name='category')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='color')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='brand')),
                ('size', models.CharField(blank=True, default='', max_length=20, verbose_name='size')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='closet_items/', verbose_name='cloth picture')),
                ('times_worn', models.PositiveIntegerField(default=0, verbose_name='times worn')),
                ('last_worn_at', models.DateTimeField(blank=True, null=True, verbose_name='last worn at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet_items', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'closet item',
                'verbose_name_plural': 'closet items',
                'ordering': ['-created_at'],
            },
        ),
    ]
