# Generated by Django 5.2.8 on 2026-07-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_product_id', models.CharField(db_index=True, help_text='Unique identifier from Awin network', max_length=100, unique=True, verbose_name='Awin Product ID')),
                ('name', models.CharField(help_text='Title/Name of the product', max_length=255, verbose_name='product name')),
                ('brand', models.CharField(db_index=True, help_text='Brand or merchant name', max_length=255, verbose_name='brand')),
                ('description', models.TextField(blank=True, help_text='Product description', null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product retail price', max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='GBP', help_text='Price currency code', max_length=10, verbose_name='currency')),
                ('image_url', models.URLField(blank=True, help_text='URL to the product image', max_length=1000, null=True, verbose_name='image url')),
                ('aw_deep_link', models.URLField(help_text='Affiliate redirect link with tracking parameter', max_length=1000, verbose_name='Awin deep link')),
                ('category', models.CharField(blank=True, db_index=True, help_text='Product category/hierarchy', max_length=255, null=True, verbose_name='category')),
                ('advertiser_name', models.CharField(blank=True, help_text='Advertiser company name', max_length=255, null=True, verbose_name='advertiser name')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this product is currently active/in-stock', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'affiliate product',
                'verbose_name_plural': 'affiliate products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['aw_product_id'], name='affiliate_a_aw_prod_41c418_idx'), models.Index(fields=['brand', 'is_active'], name='affiliate_a_brand_258712_idx'), models.Index(fields=['category', 'is_active'], name='affiliate_a_categor_3368b6_idx')],
            },
        ),
    ]
